#pragma once
#include "Pen.hpp"
#include "Object.hpp"

enum BUTTONEVENTS
{
   BUTTON_SAVE, 
   BUTTON_CHANGE_COLOR_RED,
   BUTTON_CHANGE_COLOR_YELLOw,
   BUTTON_CHANGE_COLOR_BLUE,
   BUTTON_CHANGE_COLOR_GREEN,
   BUTTON_CHANGE_COLOR_PINK,
   BUTTON_CHANGE_COLOR_PURPLE,
   BUTTON_CHANGE_COLOR_WHITE,
   BUTTON_CHANGE_COLOR_GREY,
   BUTTON_CHANGE_COLOR_BLACK,
};

void changePenColor(Pen *pen, u32 color);